# Numpy

In [1]:
import numpy as np

Det vanligaste Numpy-objektet som används är `ndarray`, en samling värden med ett godtyckligt antal dimensioner.

`arange()`-funktionen fungerar ungefär som den inbyggda funktionen `range()`, men returnerar en `array` istället för en lista.

In [2]:
A = np.arange(1, 5)

Attributet `.ndim` innehåller antalet dimensioner.

In [3]:
A.ndim

1

Med metoden `.reshape` kan vi ändra *array*ens form, eller *shape*. 

`A.reshape(2, 2)` ger en tvådimensionell *array* med 2 rader och 2 kolumner.

In [4]:
A = A.reshape(2, 2)

In [5]:
A

array([[1, 2],
       [3, 4]])

Attributet `.shape` innehåller *arrayens* *shape*.

In [6]:
A.shape

(2, 2)

Attributet `.size` innehåller antalet element i vår *array*.

In [7]:
A.size

4

Attributet `.dtype` innehåller *array*ens datatyp. Alla element i en *array* måste ha samma datatyp.

In [8]:
A.dtype

dtype('int64')

Vi kan utföra matematiska beräkningar på vektorer och matriser.

`A * 2` resulterar i en *array* där varje värde multiplicerats med 2.

In [9]:
B = A * 2

In [10]:
B

array([[2, 4],
       [6, 8]])

Matematiska beräkningar görs precis som vnaligt i Python med matematiska operatorer som `+` för addition, `-` för subtraktion, och `*` för multiplikation.

In [11]:
A + B

array([[ 3,  6],
       [ 9, 12]])

In [12]:
A * B

array([[ 2,  8],
       [18, 32]])

`*`-operatorn multiplicerar varje element i matriserna med varandra. För att utföra matrismultiplikation används `@`-operatorn.

In [13]:
A @ B

array([[14, 20],
       [30, 44]])

In [14]:
A = np.array([1, 5, 2, 4, 1, 3]).reshape(2, 3)
B = np.array([1, 3, 3, 5, 2, 4]).reshape(3, 2)

In [15]:
A@B

array([[20, 36],
       [13, 29]])