In [42]:
import numpy as np

In [44]:
A = np.arange(1, 5)

In [48]:
A.ndim

1

In [45]:
A

array([1, 2, 3, 4])

In [51]:
A = A.reshape(2, 2)

In [56]:
A

array([[1, 2],
       [3, 4]])

In [54]:
B = A * 2

In [60]:
A

array([[1, 2],
       [3, 4]])

In [55]:
B

array([[2, 4],
       [6, 8]])

In [59]:
A * B

array([[ 2,  8],
       [18, 32]])

In [61]:
A @ B

array([[14, 20],
       [30, 44]])